# Generated by Django 3.0.2 on 2020-02-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=10000)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountBasic')),
            ],
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('cid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_comment', to='comment.RowComment')),
                ('replies', models.ManyToManyField(to='comment.RowComment')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('comments', models.ManyToManyField(related_name='commentss', to='comment.SubComment')),
            ],
        ),
    ]
