# Generated by Django 3.0.2 on 2020-01-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_id', models.BigIntegerField()),
                ('comment', models.CharField(default='', max_length=300)),
                ('creator_id', models.CharField(default='', max_length=300)),
                ('creation_time', models.DateField(auto_now=True)),
                ('edited_time', models.DateField(null=True)),
                ('comment_replied_to_id', models.BigIntegerField(null=True)),
                ('image_name', models.CharField(max_length=60, null=True)),
                ('like_counter', models.IntegerField(default=0)),
                ('dislike_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
