# Generated by Django 3.0.2 on 2020-01-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200130_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited_time',
            field=models.TimeField(null=True),
        ),
    ]
