# Generated by Django 3.0.2 on 2020-01-31 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200130_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 31, 16, 8, 50, 617864), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.TimeField(default=datetime.time(16, 8, 50, 617864), editable=False),
        ),
    ]
