# Generated by Django 3.0.2 on 2020-01-31 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200131_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 31, 18, 41, 10, 162745), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.TimeField(default=datetime.time(18, 41, 10, 162745), editable=False),
        ),
    ]
