# Generated by Django 3.0.2 on 2020-01-31 15:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20200131_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.TimeField(default=datetime.time(15, 12, 55, 677506), editable=False),
        ),
    ]
