# Generated by Django 3.0.2 on 2020-01-31 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20200131_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 31, 15, 14, 6, 230426, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.TimeField(default=datetime.time(15, 14, 6, 230426), editable=False),
        ),
    ]
