# Generated by Django 3.0.2 on 2020-02-03 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20200131_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 3, 13, 31, 35, 36531, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.TimeField(default=datetime.time(13, 31, 35, 36569), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creator_id',
            field=models.CharField(max_length=300),
        ),
    ]
