# Generated by Django 3.0.2 on 2020-02-03 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20200203_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 3, 14, 9, 5, 25269, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.TimeField(default=datetime.time(14, 9, 5, 25305), editable=False),
        ),
    ]
