# Generated by Django 3.0.2 on 2020-01-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200130_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ndislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='nlikes',
            field=models.IntegerField(default=0),
        ),
    ]
