# Generated by Django 3.0.2 on 2020-02-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_accountfollowtype'),
        ('post', '0006_auto_20200131_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ndislikes',
        ),
        migrations.AddField(
            model_name='post',
            name='ndislikes',
            field=models.ManyToManyField(related_name='ndislikes', to='account.AccountBasic'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='nlikes',
        ),
        migrations.AddField(
            model_name='post',
            name='nlikes',
            field=models.ManyToManyField(related_name='nlikes', to='account.AccountBasic'),
        ),
    ]
