# Generated by Django 3.0.2 on 2020-02-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200201_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('number', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
