# Generated by Django 3.0.2 on 2020-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200203_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='name',
            field=models.CharField(default='awsome', max_length=100, primary_key=True, serialize=False),
        ),
    ]
