# Generated by Django 3.0.2 on 2020-02-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200203_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='name',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
