# Generated by Django 3.0.2 on 2020-02-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200203_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='name',
        ),
        migrations.AddField(
            model_name='number',
            name='identify',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
