# Generated by Django 3.0.2 on 2020-02-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_number_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='identify',
            field=models.CharField(default='1', max_length=10, primary_key=True, serialize=False),
        ),
    ]
