# Generated by Django 3.0.2 on 2020-02-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20200203_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='identify',
            new_name='x',
        ),
    ]
