# Generated by Django 3.0.2 on 2020-02-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20200203_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
