# Generated by Django 3.0.2 on 2020-02-05 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='follows', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='post.Post')),
                ('saccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saccount_comments', to='account.AccountBasic')),
                ('taccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taccount_comments', to='account.AccountBasic')),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='follows', max_length=20)),
                ('saccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saccount_follows', to='account.AccountBasic')),
                ('taccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taccount_follows', to='account.AccountBasic')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account', serialize=False, to='account.AccountBasic')),
                ('comments', models.ManyToManyField(related_name='comments', to='notification.Comments')),
                ('follows', models.ManyToManyField(related_name='follows', to='notification.Follows')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='like', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='post.Post')),
                ('saccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saccount_like', to='account.AccountBasic')),
                ('taccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taccount_like', to='account.AccountBasic')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='dislike', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_dislike', to='post.Post')),
                ('saccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saccount_dislike', to='account.AccountBasic')),
                ('taccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taccount_dislike', to='account.AccountBasic')),
            ],
        ),
    ]
