# Generated by Django 3.0.2 on 2020-02-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dislike',
            field=models.ManyToManyField(related_name='dislike', to='notification.Comments'),
        ),
        migrations.AddField(
            model_name='notification',
            name='like',
            field=models.ManyToManyField(related_name='like', to='notification.Comments'),
        ),
    ]
