# Generated by Django 3.0.2 on 2020-02-04 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBasic',
            fields=[
                ('username', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=200)),
                ('profile', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=20)),
                ('bio', models.CharField(default='', max_length=500)),
                ('phone_number', models.BigIntegerField(default=0)),
                ('country', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoggInBasic',
            fields=[
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.AccountBasic')),
                ('token', models.CharField(max_length=110)),
                ('token_gen_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
