# Generated by Django 3.0.2 on 2020-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200126_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBasic',
            fields=[
                ('username', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
