# Generated by Django 3.0.2 on 2020-01-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200126_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggInBasic',
            fields=[
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.AccountBasic')),
                ('token', models.CharField(max_length=75)),
                ('token_gen_time', models.DateField()),
            ],
        ),
    ]
