# Generated by Django 3.0.2 on 2020-01-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_logginbasic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logginbasic',
            name='token_gen_time',
            field=models.DateTimeField(),
        ),
    ]
