# Generated by Django 3.0.2 on 2020-01-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accountfollowtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountFollowType',
        ),
    ]
