# Generated by Django 3.0.2 on 2020-01-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200128_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logginbasic',
            name='token_gen_time',
            field=models.DateField(),
        ),
    ]
