# Generated by Django 3.0.2 on 2020-01-28 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200128_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logginbasic',
            name='token_gen_time',
            field=models.DateField(default=datetime.datetime(2020, 1, 28, 15, 1, 26, 718430)),
        ),
    ]
