# Generated by Django 3.0.2 on 2020-01-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200128_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logginbasic',
            name='token_gen_time',
        ),
    ]
