# Generated by Django 3.0.2 on 2020-01-28 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_logginbasic_token_gen_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='logginbasic',
            name='token_gen_time',
            field=models.DateField(default=datetime.datetime(2020, 1, 28, 15, 4, 32, 699081)),
        ),
    ]
