# Generated by Django 3.0.2 on 2020-01-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_logginbasic_token_gen_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logginbasic',
            name='token_gen_time',
        ),
    ]
