# Generated by Django 3.0.2 on 2020-01-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_logginbasic_token_gen_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='logginbasic',
            name='token_gen_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
