# Generated by Django 3.0.2 on 2020-01-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200129_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbasic',
            name='profile',
            field=models.ImageField(default='', upload_to='statics/profiles'),
        ),
    ]
