# Generated by Django 3.0.2 on 2020-01-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_accountbasic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbasic',
            name='profile',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
