# Generated by Django 3.0.2 on 2020-01-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200131_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbasic',
            name='profile',
            field=models.ImageField(default='', upload_to='statics/profiles'),
        ),
    ]
