# Generated by Django 3.0.2 on 2020-01-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200131_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbasic',
            name='bio',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='accountbasic',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbasic',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbasic',
            name='phone_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
