# Generated by Django 3.0.2 on 2020-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200131_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbasic',
            name='profile',
            field=models.CharField(default='', max_length=100),
        ),
    ]
