# Generated by Django 3.0.2 on 2020-02-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200131_1730'),
        ('account', '0005_delete_accountfollowtype'),
    ]

    operations = [
    ]
