# Generated by Django 3.0.2 on 2020-02-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFollowType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('follower_id', models.CharField(max_length=15)),
                ('followed_id', models.CharField(max_length=15)),
            ],
        ),
    ]
