# Generated by Django 3.0.2 on 2020-01-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountfollowtype',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
