# Generated by Django 3.0.2 on 2020-02-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('name', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
