# Generated by Django 3.0.2 on 2020-02-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200201_2036'),
        ('account_generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgeneric',
            name='posts',
            field=models.ManyToManyField(related_name='post', to='post.Post'),
        ),
    ]
